steps:
  - name: "gcr.io/cloud-builders/cloud-sql-proxy"
    args:
      - "-instances=bluf-489122:northamerica-northeast1:bluf2020=tcp:5432"
    waitFor: ["-"]

  - name: "hashicorp/terraform:latest"
    args: ["init"]
    dir: "terraform"

  - name: "hashicorp/terraform:latest"
    args: ["plan", "-out=tfplan"]
    dir: "terraform"

  - name: "hashicorp/terraform:latest"
    args: ["apply", "-auto-approve", "tfplan"]
    dir: "terraform"

options:
  logging: CLOUD_LOGGING_ONLY
