steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "terraform-with-proxy"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.8.1/cloud-sql-proxy.linux.amd64
        chmod +x cloud-sql-proxy
        ./cloud-sql-proxy --address 0.0.0.0 --port 5432 bluf-489122:northamerica-northeast1:bluf2020 & 
        sleep 5
        cd terraform
        terraform init
        terraform apply -auto-approve

options:
  logging: CLOUD_LOGGING_ONLY
